# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  condition: 

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'

- task: CmdLine@2
  displayName: 'OctoTool Install'
  inputs:
    script: 'dotnet tool install Octopus.DotNet.Cli --global'

- task: CmdLine@2
  displayName: 'Publish and Pack'
  inputs:
    script: |
      dotnet publish CedarWepApp
      dotnet-octo pack --id=CedarWebApp
